name: Test JMeter Action

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v3.1
        with:
    # jmeter test plan to execute
         test-plan-path: jmeter.jmx
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
         name: jmeter-results
         path: result.jtl
         
     - name: Run tests
        # ... your test step here
     - name: Notify slack success
     if: success()
     env:
       SLACK_BOT_TOKEN: ${{ xoxe-1-My0xLTM3MDA5NjMzNDM2ODYtNDA2OTEzNTcwMzY4MC00MDQ1MzMxODg5Mzk1LWFlMGNjNTE1NmJiOTRlNzQwODNjNDY2ZGIwNzRlNDdkNjU4ZjkyNjMwY2JiYzczMGU4ODJhMDdjM2MzMzJkNDM }}
     uses: voxmedia/github-action-slack-notify-build@v1
     with:
       channel: app-alerts
       status: SUCCESS
       color: good

     - name: Notify slack fail
       if: failure()
       env:
         SLACK_BOT_TOKEN: ${{ xoxe-1-My0xLTM3MDA5NjMzNDM2ODYtNDA2OTEzNTcwMzY4MC00MDQ1MzMxODg5Mzk1LWFlMGNjNTE1NmJiOTRlNzQwODNjNDY2ZGIwNzRlNDdkNjU4ZjkyNjMwY2JiYzczMGU4ODJhMDdjM2MzMzJkNDM }}
       uses: voxmedia/github-action-slack-notify-build@v1
       with:
         channel: app-alerts
         status: FAILED
         color: danger
