name: Test JMeter Action

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    #environment: Production
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
        status: starting
        channel: '#jmeter'
        message: Slack Success and Fail...
      if: always()

      
    - name: PerfAction for JMeter
      uses: QAInsights/PerfAction@v3.1
      with:
    # jmeter test plan to execute
         test-plan-path: jmeter.jmx
          
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
         name: jmeter-results
         path: result.jtl
         
   
         
     
   
