on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: jmeter.jmx
          args: ""
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
          
      - name: toggle workflow command echoing
        run: |
          ls -lrt
          echo '::set-output name=action_echo::disabled'
          echo '::echo::on'
          echo '::set-output name=action_echo::enabled'
          echo '::echo::off'
          echo '::set-output name=action_echo::disabled'
        
