name: Test JMeter Action

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v3.1
        with:
    # jmeter test plan to execute
         test-plan-path: jmeter.jmx
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
         name: jmeter-results
         path: result.jtl
         
     
    
