name: Test JMeter Action

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v3.1
        with:
    # jmeter test plan to execute
         test-plan-path: jmeter.jmx
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
         name: jmeter-results
         path: result.jtl
         
     
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: "xoxe.xoxp-1-Mi0yLTM3MDA5NjMzNDM2ODYtMzcwNzUxMzUzNDExNS00MDY5MTM1NzAzNjgwLTQwNTkzMzcxMTE3NjYtNzI1NjY3OTI2OWU2M2FhNjAyYWNkMTI2ZmI2MDBjNDY5ZGJhOTFiNTcwNWI0NWM0NTQxZTlkYTExYjFjZGE5MA"
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: jmeter
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: "xoxe.xoxp-1-Mi0yLTM3MDA5NjMzNDM2ODYtMzcwNzUxMzUzNDExNS00MDY5MTM1NzAzNjgwLTQwNTkzMzcxMTE3NjYtNzI1NjY3OTI2OWU2M2FhNjAyYWNkMTI2ZmI2MDBjNDY5ZGJhOTFiNTcwNWI0NWM0NTQxZTlkYTExYjFjZGE5MA"
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: jmeter
          status: FAILED
          color: danger
